import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:PiliPlus/models_new/youtube/yt_video_detail.dart';
import 'package:PiliPlus/services/youtube/yt_innertube_player.dart';
import 'package:PiliPlus/utils/yt_auth.dart';

class YtMuxedStreamOption {
  /// 视频流 URL。muxed 时这是合并流(含音);split 时这是 video-only,
  /// 需配合 [audioUrl] 通过 `player.setAudioTrack(AudioTrack.uri(audioUrl))` 注入音频
  final String url;
  /// 高画质所需的外部音频流 URL。muxed 流时为 null
  final String? audioUrl;
  final String qualityLabel; // e.g. "720p"
  final int bitrate;
  const YtMuxedStreamOption({
    required this.url,
    required this.qualityLabel,
    required this.bitrate,
    this.audioUrl,
  });

  bool get isSplit => audioUrl != null;
}

class YtSubtitleTrackInfo {
  /// 在 UI 显示的语言名(如"中文"、"English"、"自动生成 中文")
  final String label;
  /// VTT 格式字幕 URL(YT timedtext API,已 append `&fmt=vtt`)
  final String url;
  final String langCode; // e.g. "zh-Hans", "en"
  final bool isAutoGenerated;
  const YtSubtitleTrackInfo({
    required this.label,
    required this.url,
    required this.langCode,
    required this.isAutoGenerated,
  });
}

class YtVideoService {
  /// 拿视频元信息
  Future<YtVideoDetail> fetchDetail(String videoId) async {
    final yt = YoutubeExplode();
    try {
      final v = await yt.videos.get(VideoId(videoId));
      return YtVideoDetail(
        videoId: v.id.value,
        title: v.title,
        author: v.author,
        duration: v.duration,
        viewCount: v.engagement.viewCount,
        likeCount: v.engagement.likeCount,
        description: v.description,
        thumbnailUrl: v.thumbnails.highResUrl,
        uploadDate: v.uploadDate,
        keywords: v.keywords.toList(),
      );
    } finally {
      yt.close();
    }
  }

  /// 拿 muxed 流 URL。返回 null 时表示无可用 muxed 流。
  /// 选最高 bitrate 的 muxed 流。
  Future<String?> fetchMuxedUrl(String videoId) async {
    final streams = await fetchMuxedStreams(videoId);
    if (streams.isEmpty) return null;
    return streams.first.url;
  }

  /// 拿全部 muxed 流(按 bitrate 降序),用于画质切换 UI
  static String _qualityLabel(String enumName) {
    // youtube_explode_dart 的 VideoQuality 枚举名形如 "high720" / "medium360"
    final m = RegExp(r'\d+').firstMatch(enumName);
    return m != null ? '${m.group(0)}p' : enumName;
  }

  /// 拿全部 native 字幕轨道列表(不预生成翻译选项,翻译留给 UI 层动态拼)。
  /// 每条 track 保留原始 URL,需要翻译时拼 `&tlang=lang` 参数。
  Future<List<YtSubtitleTrackInfo>> fetchSubtitleTracks(String videoId) async {
    final yt = YoutubeExplode();
    try {
      final manifest =
          await yt.videos.closedCaptions.getManifest(VideoId(videoId));
      final out = <YtSubtitleTrackInfo>[];
      for (final t in manifest.tracks) {
        out.add(YtSubtitleTrackInfo(
          label: t.isAutoGenerated
              ? '${t.language.name}(自动生成)'
              : t.language.name,
          url: _toVttUrl(t.url),
          langCode: t.language.code,
          isAutoGenerated: t.isAutoGenerated,
        ));
      }
      // 排序: 中文优先 → 非自动生成优先 → 字母序
      out.sort((a, b) {
        final aZh = a.langCode.startsWith('zh') ? 0 : 1;
        final bZh = b.langCode.startsWith('zh') ? 0 : 1;
        if (aZh != bZh) return aZh.compareTo(bZh);
        final aAuto = a.isAutoGenerated ? 1 : 0;
        final bAuto = b.isAutoGenerated ? 1 : 0;
        if (aAuto != bAuto) return aAuto.compareTo(bAuto);
        return a.label.compareTo(b.label);
      });
      return out;
    } catch (_) {
      return const [];
    } finally {
      yt.close();
    }
  }

  /// 把 native track URL 转成"自动翻译为 [tlang]"的 URL
  static String translateUrl(String nativeUrl, String tlang) {
    final uri = Uri.parse(nativeUrl);
    final params = Map<String, dynamic>.from(uri.queryParameters);
    params['tlang'] = tlang;
    return uri.replace(queryParameters: params).toString();
  }

  /// YT 自动翻译支持的常用目标语言(完美复刻 YT app 字幕菜单 "自动翻译")
  /// 实际 YT 支持 100+ 种,这里挑常见 25 种
  static const translateTargets = <({String code, String name})>[
    (code: 'zh-Hans', name: '中文(简体)'),
    (code: 'zh-Hant', name: '中文(繁體)'),
    (code: 'en', name: '英语'),
    (code: 'ja', name: '日语'),
    (code: 'ko', name: '韩语'),
    (code: 'es', name: '西班牙语'),
    (code: 'fr', name: '法语'),
    (code: 'de', name: '德语'),
    (code: 'ru', name: '俄语'),
    (code: 'pt', name: '葡萄牙语'),
    (code: 'it', name: '意大利语'),
    (code: 'ar', name: '阿拉伯语'),
    (code: 'hi', name: '印地语'),
    (code: 'tr', name: '土耳其语'),
    (code: 'vi', name: '越南语'),
    (code: 'th', name: '泰语'),
    (code: 'id', name: '印度尼西亚语'),
    (code: 'ms', name: '马来语'),
    (code: 'pl', name: '波兰语'),
    (code: 'nl', name: '荷兰语'),
    (code: 'sv', name: '瑞典语'),
    (code: 'no', name: '挪威语'),
    (code: 'fi', name: '芬兰语'),
    (code: 'da', name: '丹麦语'),
    (code: 'cs', name: '捷克语'),
  ];

  static String _toVttUrl(Uri original, {String? tlang}) {
    // YT timedtext API 默认返回 XML;append `&fmt=vtt` 让其返回 WebVTT
    final params = Map<String, dynamic>.from(original.queryParameters);
    params['fmt'] = 'vtt';
    if (tlang != null) params['tlang'] = tlang;
    return original.replace(queryParameters: params).toString();
  }

  /// 按当前最稳排序;yt_explode 内部 try-all fallback。
  /// 2026-05-19 dual-client 起步:androidVr / safari / mweb 优先(yt-dlp 推荐组合)
  static final _streamClients = [
    YoutubeApiClient.androidVr,
    YoutubeApiClient.safari,
    YoutubeApiClient.mweb,
    YoutubeApiClient.android,
    YoutubeApiClient.androidSdkless,
    YoutubeApiClient.ios,
    YoutubeApiClient.tv,
  ];

  /// 取所有可用画质选项:
  /// - muxed 流(360p 及以下,含音)
  /// - video-only 流(720p / 1080p / ...,无音 → 配合最佳 audio-only 流注入)
  /// 同一画质有 muxed 优先选 muxed(单流更稳)。
  ///
  /// 优先用 **Innertube + poToken** (NewPipe 路线,解锁 1080p+/4K);
  /// 热备链:ANDROID_VR(免登录) → MWEB(登录态)→ yt_explode 360p
  /// 任一返回非空 list 立即采用,全失败 throw 三段诊断
  Future<List<YtMuxedStreamOption>> fetchMuxedStreams(String videoId) async {
    Object? avrErr;
    Object? mwebErr;
    Object? explodeErr;

    // [1] ANDROID_VR(免登录主路径)
    try {
      // ignore: avoid_print
      print('[YtVideo] Trying ANDROID_VR for $videoId...');
      final resp = await YtInnertubePlayer.fetchPlayer(
        videoId,
        client: YtInnertubeClient.androidVr,
      ).timeout(const Duration(seconds: 25));
      // ignore: avoid_print
      print('[YtVideo] ANDROID_VR OK, ${resp.formats.length} formats, hls=${resp.hlsManifestUrl != null}');
      final out = _innertubeToMuxedOptions(resp);
      if (out.isNotEmpty) return out;
    } catch (e) {
      avrErr = e;
      // ignore: avoid_print
      print('[YtVideo] ANDROID_VR FAILED: $e');
    }

    // [2] MWEB(登录态;未登录跳过)
    if (YtAuthService.isLoggedIn) {
      try {
        // ignore: avoid_print
        print('[YtVideo] Trying MWEB for $videoId...');
        final resp = await YtInnertubePlayer.fetchPlayer(
          videoId,
          client: YtInnertubeClient.mweb,
        ).timeout(const Duration(seconds: 25));
        // ignore: avoid_print
        print('[YtVideo] MWEB OK, ${resp.formats.length} formats');
        final out = _innertubeToMuxedOptions(resp);
        if (out.isNotEmpty) return out;
      } catch (e) {
        mwebErr = e;
        // ignore: avoid_print
        print('[YtVideo] MWEB FAILED: $e');
      }
    }

    // [3] yt_explode_dart 兜底
    for (var attempt = 0; attempt < 2; attempt++) {
      try {
        final out = await _fetchMuxedOnce(videoId);
        if (out.isNotEmpty) return out;
      } catch (e) {
        explodeErr = e;
        if (attempt == 0) {
          await Future<void>.delayed(const Duration(milliseconds: 500));
        }
      }
    }

    final buf = StringBuffer('取流失败\n');
    buf.writeln('[1] ANDROID_VR: ${avrErr ?? '(空 stream)'}');
    buf.writeln('[2] MWEB: ${YtAuthService.isLoggedIn ? (mwebErr ?? '(空 stream)') : '(未登录,跳过)'}');
    buf.writeln('[3] yt_explode: ${explodeErr ?? '(空 stream)'}');
    throw Exception(buf.toString());
  }

  /// 把 Innertube 返回的 27 formats 转成 (画质标签 → URL) 列表。
  /// 加入 HLS master 作为"自动"选项 — libmpv 自己处理 demux 和 ABR
  /// 同画质多 codec 时优先 mp4+H.264。
  static List<YtMuxedStreamOption> _innertubeToMuxedOptions(
      YtInnertubePlayerResponse resp) {
    final extra = <YtMuxedStreamOption>[];
    // HLS master:libmpv 直接读 m3u8,把音视频整在一起;最稳的高画质路径
    if (resp.hlsManifestUrl != null) {
      extra.add(YtMuxedStreamOption(
        url: resp.hlsManifestUrl!,
        qualityLabel: '自动 (HLS)',
        bitrate: 0,
      ));
    }
    // 1) 选最佳 audio:非 dubbed,优先 m4a (mp4 container,兼容性最好)
    String? mp4Audio;
    String? webmAudio;
    final audioList = resp.formats.where((f) => !f.hasVideo && f.hasAudio).toList()
      ..sort((a, b) => b.bitrate.compareTo(a.bitrate));
    for (final a in audioList) {
      if (a.isDubbedAudio) continue;
      if (a.container == 'mp4' || a.container == 'm4a') {
        mp4Audio ??= a.url;
      } else if (a.container == 'webm') {
        webmAudio ??= a.url;
      }
      if (mp4Audio != null && webmAudio != null) break;
    }
    // 兜底:全 dubbed 时挑最高 bitrate
    if (mp4Audio == null && webmAudio == null && audioList.isNotEmpty) {
      for (final a in audioList) {
        if (a.container == 'mp4' || a.container == 'm4a') {
          mp4Audio ??= a.url;
        } else if (a.container == 'webm') {
          webmAudio ??= a.url;
        }
        if (mp4Audio != null && webmAudio != null) break;
      }
    }

    // 2) 收 muxed (progressive,通常仅 360p / 720p / 1080p 旧规格);Innertube iOS 给的少
    final out = <YtMuxedStreamOption>[];
    final seen = <String>{};
    int codecPriority(String codec) {
      if (codec.startsWith('avc1')) return 0;
      if (codec.startsWith('vp9')) return 1;
      if (codec.startsWith('av01')) return 2;
      return 3;
    }
    int containerPriority(String c) =>
        c == 'mp4' ? 0 : c == 'webm' ? 1 : 2;

    final muxed = resp.formats.where((f) => f.hasVideo && f.hasAudio).toList()
      ..sort((a, b) => (b.height ?? 0).compareTo(a.height ?? 0));
    for (final f in muxed) {
      final label = f.qualityLabel ?? '${f.height ?? 0}p';
      if (!seen.add(label)) continue;
      out.add(YtMuxedStreamOption(
        url: f.url,
        qualityLabel: label,
        bitrate: f.bitrate,
      ));
    }

    // 3) 收 video-only (split,需要 audioUrl 注入)
    final videoOnly = resp.formats.where((f) => f.hasVideo && !f.hasAudio).toList();
    // 按 height desc, container, codec 排
    videoOnly.sort((a, b) {
      final h = (b.height ?? 0).compareTo(a.height ?? 0);
      if (h != 0) return h;
      final cp = containerPriority(a.container).compareTo(containerPriority(b.container));
      if (cp != 0) return cp;
      return codecPriority(a.codec).compareTo(codecPriority(b.codec));
    });
    for (final f in videoOnly) {
      final label = f.qualityLabel ?? '${f.height ?? 0}p';
      if (!seen.add(label)) continue;
      final matched = f.container == 'mp4'
          ? (mp4Audio ?? webmAudio)
          : (webmAudio ?? mp4Audio);
      if (matched == null) continue;
      out.add(YtMuxedStreamOption(
        url: f.url,
        audioUrl: matched,
        qualityLabel: label,
        bitrate: f.bitrate,
      ));
    }

    // 按画质降序
    out.sort((a, b) {
      int n(String l) => int.tryParse(l.replaceAll(RegExp(r'[^0-9]'), '')) ?? 0;
      return n(b.qualityLabel).compareTo(n(a.qualityLabel));
    });
    // HLS 自动放最前面(默认首选)
    return [...extra, ...out];
  }

  Future<List<YtMuxedStreamOption>> _fetchMuxedOnce(String videoId) async {
    final yt = YoutubeExplode();
    try {
      final manifest = await yt.videos.streamsClient.getManifest(
        videoId,
        ytClients: _streamClients,
      );
      // 为每个 container 选最佳 audio:mp4/m4a video-only 流要配 mp4 audio,
      // webm 配 webm。跨容器在 libmpv 上不稳(实测黑屏 / 不前进)。
      // 过滤 dubbed audio(YT 多语言配音轨道,URL 含 acont=dubbed),
      // 否则会自动选俄语 / 日语等 dubbed 版本覆盖原声。
      String? mp4AudioUrl;
      String? webmAudioUrl;
      for (final s in manifest.audioOnly.toList()
        ..sort((a, b) => b.bitrate.compareTo(a.bitrate))) {
        final urlStr = s.url.toString();
        final isDubbed = urlStr.contains('acont%3Ddubbed') ||
            urlStr.contains('acont=dubbed') ||
            urlStr.contains('xtags=acont');
        if (isDubbed) continue;
        final c = s.container.name.toLowerCase();
        if ((c == 'mp4' || c == 'm4a') && mp4AudioUrl == null) {
          mp4AudioUrl = urlStr;
        } else if (c == 'webm' && webmAudioUrl == null) {
          webmAudioUrl = urlStr;
        }
        if (mp4AudioUrl != null && webmAudioUrl != null) break;
      }
      // fallback: 如果全部 audio 都是 dubbed(罕见),退回选最高 bitrate 的
      if (mp4AudioUrl == null && webmAudioUrl == null &&
          manifest.audioOnly.isNotEmpty) {
        final fallbackSorted = manifest.audioOnly.toList()
          ..sort((a, b) => b.bitrate.compareTo(a.bitrate));
        for (final s in fallbackSorted) {
          final c = s.container.name.toLowerCase();
          if ((c == 'mp4' || c == 'm4a') && mp4AudioUrl == null) {
            mp4AudioUrl = s.url.toString();
          } else if (c == 'webm' && webmAudioUrl == null) {
            webmAudioUrl = s.url.toString();
          }
          if (mp4AudioUrl != null && webmAudioUrl != null) break;
        }
      }
      // 收集 muxed 流(单流含音)
      final muxedSorted = manifest.muxed.toList()
        ..sort((a, b) => b.bitrate.compareTo(a.bitrate));
      final out = <YtMuxedStreamOption>[];
      final seenLabels = <String>{};
      for (final s in muxedSorted) {
        final label = _qualityLabel(s.videoQuality.name);
        if (seenLabels.add(label)) {
          out.add(YtMuxedStreamOption(
            url: s.url.toString(),
            qualityLabel: label,
            bitrate: s.bitrate.bitsPerSecond,
          ));
        }
      }
      // 收集 video-only 流(高画质,需外部 audio 注入)
      // 登录态把 cookie 注入 mpv setMediaHeader 后可放开。
      final authEnabled = YtAuthService.isLoggedIn;
      if (authEnabled) {
        _collectSplitStreams(
          manifest,
          mp4AudioUrl: mp4AudioUrl,
          webmAudioUrl: webmAudioUrl,
          out: out,
          seenLabels: seenLabels,
        );
      }
      // 按画质数值降序(720>360>240)
      out.sort((a, b) {
        int n(String l) =>
            int.tryParse(l.replaceAll(RegExp(r'[^0-9]'), '')) ?? 0;
        return n(b.qualityLabel).compareTo(n(a.qualityLabel));
      });
      return out;
    } finally {
      yt.close();
    }
  }

  /// 收集 split 高画质流(video-only + 外部 audio)
  ///
  /// 暂未启用 — YT 对无 cookie 请求返回 403。等接入登录后可调用。
  /// 同画质有多个 codec 时优先 mp4+H.264;AV1/VP9 mac/ios 可能解码不畅。
  void _collectSplitStreams(
    StreamManifest manifest, {
    required String? mp4AudioUrl,
    required String? webmAudioUrl,
    required List<YtMuxedStreamOption> out,
    required Set<String> seenLabels,
  }) {
    if ((mp4AudioUrl == null && webmAudioUrl == null) ||
        manifest.videoOnly.isEmpty) {
      return;
    }
    int containerPriority(String name) {
      final c = name.toLowerCase();
      if (c == 'mp4') return 0;
      if (c == 'webm') return 1;
      return 2;
    }
    int codecPriority(String codec) {
      if (codec.startsWith('avc1')) return 0;
      if (codec.startsWith('vp9')) return 1;
      if (codec.startsWith('av01')) return 2;
      return 3;
    }
    final voSorted = manifest.videoOnly.toList()
      ..sort((a, b) {
        int qa(String l) =>
            int.tryParse(l.replaceAll(RegExp(r'[^0-9]'), '')) ?? 0;
        final q = qa(_qualityLabel(b.videoQuality.name))
            .compareTo(qa(_qualityLabel(a.videoQuality.name)));
        if (q != 0) return q;
        final cp = containerPriority(a.container.name)
            .compareTo(containerPriority(b.container.name));
        if (cp != 0) return cp;
        return codecPriority(a.videoCodec)
            .compareTo(codecPriority(b.videoCodec));
      });
    for (final s in voSorted) {
      final label = _qualityLabel(s.videoQuality.name);
      if (!seenLabels.add(label)) continue;
      final vc = s.container.name.toLowerCase();
      final matchedAudio = (vc == 'mp4'
              ? mp4AudioUrl
              : (vc == 'webm' ? webmAudioUrl : null)) ??
          mp4AudioUrl ??
          webmAudioUrl;
      if (matchedAudio == null) continue;
      out.add(YtMuxedStreamOption(
        url: s.url.toString(),
        audioUrl: matchedAudio,
        qualityLabel: label,
        bitrate: s.bitrate.bitsPerSecond,
      ));
    }
  }

  /// (旧签名,保留兼容)
  Future<List<YtMuxedStreamOption>> fetchMuxedStreamsLegacy(
      String videoId) async {
    final yt = YoutubeExplode();
    try {
      final manifest = await yt.videos.streamsClient.getManifest(videoId);
      if (manifest.muxed.isEmpty) return const [];
      final sorted = manifest.muxed.toList()
        ..sort((a, b) => b.bitrate.compareTo(a.bitrate));
      return [
        for (final s in sorted)
          YtMuxedStreamOption(
            url: s.url.toString(),
            qualityLabel: _qualityLabel(s.videoQuality.name),
            bitrate: s.bitrate.bitsPerSecond,
          ),
      ];
    } finally {
      yt.close();
    }
  }
}
